version: '0.1.0'

services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
    networks:
      - graphpedia-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: elasticsearch_service
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "discovery.type=single-node"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - graphpedia-network

  index-setup:
    image: curlimages/curl:7.85.0
    container_name: elasticsearch_index_setup
    entrypoint: ["sh", "-c"]
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    command: |
      until curl -sS -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} "http://localhost:9200/_cat/health?h=status" | grep -q "green\|yellow"; do
        sleep 1
      done
      curl -X PUT "http://localhost:9200/term_context" -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} -H "Content-Type: application/json" -d'
      {
        "mappings": {
          "properties": {
            "_class": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "article": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "createdDate": {
              "type": "date",
              "format": "yyyy-MM-dd'T'HH:mm:ss"
            },
            "id": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "searched": {
              "type": "boolean"
            },
            "source": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "synonyms": {
              "type": "keyword"
            },
            "title": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "updatedDate": {
              "type": "date",
              "format": "yyyy-MM-dd'T'HH:mm:ss"
            }
          }
        },
        "settings": {
          "index": {
            "routing": {
              "allocation": {
                "include": {
                  "_tier_preference": "data_content"
                }
              }
            },
            "number_of_shards": "1",
            "provided_name": "term_context",
            "creation_date": "1731192141984",
            "number_of_replicas": "1",
            "uuid": "mv7B7fyTS5WqF1wYRJAyqg",
            "version": {
              "created": "7172399"
            }
          }
        }
      }'
    networks:
      - graphpedia-network
    depends_on:
      - elasticsearch

volumes:
  neo4j_data:
  es_data:

networks:
  graphpedia-network:
    driver: bridge
    external: true
